project:
  type: website
  output-dir: _site
  pre-render: 
    - bash assets/bash/generate_thumbs.sh
 
  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true


  resources:
    - "assets/**"
    - "images/**"
    - "data/**"
    - "files/**"
    - "posts/**"

    # Things that need to be at the site root
    - "pgp_ath.asc.txt"



website:
  title: "Anthony Faustine"
  description: "Lead Data Scientist at the Centre for Intelligent Power (CIP) at Eaton in Dublin, Ireland"
  favicon: "/images/icons/favicon.ico"
  site-url: "https://sambaiga.github.io"
  repo-url: "https://github.com/sambaiga/sambaiga.github.io"
  page-navigation: true
 


  open-graph:
    title: "Anthony Faustine"
    description: "Lead Data Scientist at the Centre for Intelligent Power (CIP) at Eaton"
    image: ""
    locale: en_IE

  twitter-card: 
    card-style: summary_large_image
    creator: "@asambaiga"
    site: "@sambaiga"

  navbar:
    pinned: true
    collapse: true
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        file: "pages/about/index.qmd"
      - text: "Blog"
        file: "pages/blog/index.qmd"
      - text: "Research"
        file: "pages/publication/index.qmd"
      #- text: "Projects"
      #  file: "pages/project/index.qmd"

    right:
      - text: "{{< bi envelope-at size=1.1em >}}<span class='visually-hidden'>Email</span>"
        href: "mailto:sambaiga@gmail.com"
      - text: "{{< bi github size=1.1em >}}<span class='visually-hidden'>GitHub</span>"
        href: https://github.com/sambaiga
        rel: me
      - text: "{{< bi linkedin size=1.1em >}}<span class='visually-hidden'>LinkedIn</span>"
        href: https://www.linkedin.com/in/sambaiga
        rel: me
    
  page-footer:
    left: |
      <span class="faux-block">{{< bi cc-circle >}} {{< var years >}} Anthony Faustine</span>
      <span class="faux-block">All content licensed under<br>[{{< bi cc-circle >}} {{< bi cc-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>      
    center: |
      <span class="faux-block">{{< bi orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
      <span class="faux-block">{{< bi key >}} [PGP public key]({{< var pgp.key >}}) &emsp; {{< bi fingerprint >}} Fingerprint:</strong><br><span class="fingerprint">{{< var pgp.fingerprint >}}</span></span>
    right: |
      <span class="faux-block">Made with [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< bi github >}} GitHub]({{< var github-url >}})</span>

filters:
  - quarto

icons:
  bootstrap: true

format:
  html:
    theme: [cosmo, assets/twiga.scss]
    self-contained: false
    embed-resources: false
    responsive-images: true
    fig-align: center
    clean-urls: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    aria: true
    toc: true

freeze: auto
citation: false
execute:
  echo: true
  message: true
  warning: true



